// This file has been auto-generated by `@adobe/aio-commerce-lib-app`
// Do not modify this file directly

import { installationRuntimeAction } from "@adobe/aio-commerce-lib-app/actions/installation"
import appConfig from "#app.commerce.config";

import * as customScript0 from "../../../../../scripts/create-tax-integrations.js";

/**
 * Loads custom installation scripts defined in the manifest
 * @param {object} appConfig - Application configuration from manifest
 * @param {object} logger - Logger instance
 * @returns {Promise<object>} Object mapping script paths to loaded modules
 */
export function customScriptsLoader(appConfig, logger) {
  const customSteps = appConfig.installation?.customInstallationSteps || [];

  if (customSteps.length === 0) {
    logger.debug("No custom installation scripts configured");
    return {};
  }

  try {
    const loadedScripts = {
      "./scripts/create-tax-integrations.js": customScript0,
    };

    logger.debug(`Loaded ${Object.keys(loadedScripts).length} custom installation script(s)`);
    return loadedScripts;
  } catch (error) {
    logger.error(`Failed to load custom installation scripts: ${error.message}`);
    throw new Error(`Failed to load custom installation scripts: ${error.message}`);
  }
}

const args = { appConfig, customScriptsLoader };
export const main = installationRuntimeAction(args);
