/*
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

// This file has been auto-generated by `@adobe/aio-commerce-lib-app`
// Do not modify this file directly

import { installationRuntimeAction } from "@adobe/aio-commerce-lib-app/actions/installation"
import appConfig from "../../app.commerce.manifest.json" with { type: "json" };

import * as customScript0 from "../../../../../scripts/create-shipping-carriers.js";

/**
 * Loads custom installation scripts defined in the manifest
 * @param {object} appConfig - Application configuration from manifest
 * @param {object} logger - Logger instance
 * @returns {Promise<object>} Object mapping script paths to loaded modules
 */
export function customScriptsLoader(appConfig, logger) {
  const customSteps = appConfig.installation?.customInstallationSteps || [];

  if (customSteps.length === 0) {
    logger.debug("No custom installation scripts configured");
    return {};
  }

  try {
    const loadedScripts = {
      "./scripts/create-shipping-carriers.js": customScript0,
    };

    logger.debug(`Loaded ${Object.keys(loadedScripts).length} custom installation script(s)`);
    return loadedScripts;
  } catch (error) {
    logger.error(`Failed to load custom installation scripts: ${error.message}`);
    throw new Error(`Failed to load custom installation scripts: ${error.message}`);
  }
}

const args = { appConfig, customScriptsLoader };
export const main = installationRuntimeAction(args);
